apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-aka-gp
  namespace: openshift-gitops
spec:
  project: default 
  source:
    repoURL: https://github.com/nbst-devhub-template/helloworld-gp-manifest.git
    targetRevision: develop
    path: ./kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: helloworld-aka-gp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
    - /secrets
